name: Git Push To Remote Action
description: Push GitHub repository to remote repository.

author: Crypto Michael

inputs:
  repository:
    description: Local file path to the git repository. Default to current directory.
    required: false
    default: "."
  remote_repository:
    description: Remote repository. For example `git@gitlab.com:cryptomichael/git-push-action.git`.
    required: true
  push_options:
    description: Option for git push. For example `--force` or `--force --tags`.
    required: false
    default: ""

runs:
  using: node20
  main: index.js

branding:
  icon: corner-up-right
  color: green
